import React, { useState, useEffect } from 'react';
import { 
  Download, 
  Search, 
  RefreshCw, 
  Clock, 
  FileText, 
  FileSpreadsheet, 
  FileType 
} from 'lucide-react';
import { ExportHistoryItem } from '../../types/importExport';
import { fetchExportHistory } from '../../services/auditHistoryService';

interface ExportHistoryViewProps {
  schoolId: string;
}

export const ExportHistoryView: React.FC<ExportHistoryViewProps> = ({ schoolId }) => {
  const [history, setHistory] = useState<ExportHistoryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');

  const loadData = async () => {
    setLoading(true);
    const data = await fetchExportHistory(schoolId);
    setHistory(data);
    setLoading(false);
  };

  useEffect(() => {
    loadData();
  }, [schoolId]);

  const filtered = history.filter(item => 
    item.exportType.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.exportedByName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    item.fileFormat.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-sm space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
        <div>
          <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <Clock className="w-5 h-5 text-indigo-600" />
            Export Generation History
          </h3>
          <p className="text-xs text-slate-500">Historical archive of reports, rosters, and analytics generated by users.</p>
        </div>

        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-2.5" />
            <input
              type="text"
              placeholder="Search export type or user..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9 pr-3 py-1.5 text-xs bg-slate-50 border border-slate-200 rounded-lg w-full sm:w-60 focus:outline-none focus:ring-1 focus:ring-indigo-500"
            />
          </div>
          <button
            onClick={loadData}
            className="p-2 text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-lg transition"
            title="Refresh logs"
          >
            <RefreshCw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {loading ? (
        <div className="py-12 text-center text-xs text-slate-500">
          Loading export history...
        </div>
      ) : filtered.length === 0 ? (
        <div className="py-12 text-center text-slate-500 space-y-2">
          <Download className="w-10 h-10 text-slate-300 mx-auto" />
          <p className="text-sm font-semibold text-slate-700">No export logs found</p>
          <p className="text-xs text-slate-400">Generate reports using the Export Module to log historical exports.</p>
        </div>
      ) : (
        <div className="border border-slate-200 rounded-xl overflow-hidden">
          <table className="w-full text-left border-collapse">
            <thead className="bg-slate-100 text-[11px] font-bold text-slate-600 uppercase">
              <tr>
                <th className="py-3 px-4 border-b">Export Category</th>
                <th className="py-3 px-4 border-b">Format</th>
                <th className="py-3 px-4 border-b">Record Count</th>
                <th className="py-3 px-4 border-b">Exported By</th>
                <th className="py-3 px-4 border-b">Date & Time</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-xs">
              {filtered.map((item) => (
                <tr key={item.id} className="hover:bg-slate-50/80">
                  <td className="py-3 px-4">
                    <p className="font-bold text-slate-900 capitalize">{item.exportType.replace('-', ' ')}</p>
                    <p className="text-[11px] text-slate-400 font-mono">{item.exportId}</p>
                  </td>
                  <td className="py-3 px-4">
                    <span className={`text-[11px] font-bold px-2.5 py-0.5 rounded-full uppercase border ${
                      item.fileFormat === 'pdf' 
                        ? 'bg-rose-50 text-rose-800 border-rose-200' 
                        : item.fileFormat === 'xlsx'
                        ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                        : 'bg-amber-50 text-amber-800 border-amber-200'
                    }`}>
                      {item.fileFormat}
                    </span>
                  </td>
                  <td className="py-3 px-4 font-semibold text-slate-800">{item.recordCount} records</td>
                  <td className="py-3 px-4 text-slate-600 font-medium">{item.exportedByName}</td>
                  <td className="py-3 px-4 text-slate-500">
                    {new Date(item.exportedAt).toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
